/*----- PROTECTED REGION ID(AmptekPX5StateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        AmptekPX5StateMachine.cpp
//
// description : C++ source for the «name» and its alowed
//               methods for commands and attributes
//
// project :     AmptekPX5.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <AmptekPX5.h>
#include <AmptekPX5Class.h>

/*----- PROTECTED REGION END -----*/


/*
 * AmptekPX5 states description:
 *
 * MOVING :	 
 */

namespace AmptekPX5_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_FastCountState_allowed()
 *	Description : Execution allowed for FastCount attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_FastCount_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for FastCount attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_FastCountStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_FastCountStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_SlowCountState_allowed()
 *	Description : Execution allowed for SlowCount attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_SlowCount_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for SlowCount attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_SlowCountStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_SlowCountStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_AcquisitionTimeState_allowed()
 *	Description : Execution allowed for AcquisitionTime attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_AcquisitionTime_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::MOVING)
		{
		
	/*----- PROTECTED REGION ID(AmptekPX5::AcquisitionTimeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::AcquisitionTimeStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
		//	Not any excluded states for AcquisitionTime attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_AcquisitionTimeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_AcquisitionTimeStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_CoarseGainState_allowed()
 *	Description : Execution allowed for CoarseGain attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_CoarseGain_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::MOVING)
		{
		
	/*----- PROTECTED REGION ID(AmptekPX5::CoarseGainStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::CoarseGainStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
		//	Not any excluded states for CoarseGain attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_CoarseGainStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_CoarseGainStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_PileupRejectState_allowed()
 *	Description : Execution allowed for PileupReject attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_PileupReject_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::MOVING)
		{
		
	/*----- PROTECTED REGION ID(AmptekPX5::PileupRejectStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::PileupRejectStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
		//	Not any excluded states for PileupReject attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_PileupRejectStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_PileupRejectStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_FlatTopWidthState_allowed()
 *	Description : Execution allowed for FlatTopWidth attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_FlatTopWidth_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::MOVING)
		{
		
	/*----- PROTECTED REGION ID(AmptekPX5::FlatTopWidthStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::FlatTopWidthStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
		//	Not any excluded states for FlatTopWidth attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_FlatTopWidthStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_FlatTopWidthStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_PeakingTimeState_allowed()
 *	Description : Execution allowed for PeakingTime attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_PeakingTime_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::MOVING)
		{
		
	/*----- PROTECTED REGION ID(AmptekPX5::PeakingTimeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::PeakingTimeStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
		//	Not any excluded states for PeakingTime attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_PeakingTimeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_PeakingTimeStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_MCACState_allowed()
 *	Description : Execution allowed for MCAC attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_MCAC_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::MOVING)
		{
		
	/*----- PROTECTED REGION ID(AmptekPX5::MCACStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::MCACStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
		//	Not any excluded states for MCAC attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_MCACStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_MCACStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_FineGainState_allowed()
 *	Description : Execution allowed for FineGain attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_FineGain_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::MOVING)
		{
		
	/*----- PROTECTED REGION ID(AmptekPX5::FineGainStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::FineGainStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
		//	Not any excluded states for FineGain attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_FineGainStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_FineGainStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_TotalGainState_allowed()
 *	Description : Execution allowed for TotalGain attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_TotalGain_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for TotalGain attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_TotalGainStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_TotalGainStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_ClockState_allowed()
 *	Description : Execution allowed for Clock attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_Clock_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::MOVING)
		{
		
	/*----- PROTECTED REGION ID(AmptekPX5::ClockStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::ClockStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
		//	Not any excluded states for Clock attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_ClockStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_ClockStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_DeadTimeState_allowed()
 *	Description : Execution allowed for DeadTime attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_DeadTime_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for DeadTime attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_DeadTimeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_DeadTimeStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_SpectrumState_allowed()
 *	Description : Execution allowed for Spectrum attribute.
 */
//--------------------------------------------------------

bool AmptekPX5::is_Spectrum_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for Spectrum attribute in READ access.
	
	/*----- PROTECTED REGION ID(AmptekPX5::read_SpectrumStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_SpectrumStateAllowed_READ

	return true;
}


	/*----- PROTECTED REGION ID(AmptekPX5::are_dynamic_attributes_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic attributes are alowed

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::are_dynamic_attributes_allowed


//=================================================
//		Commands Allowed Methods
//=================================================


//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_SetTextConfigurationState_allowed()
 *	Description : Execution allowed for SetTextConfiguration command.
 */
//--------------------------------------------------------

bool AmptekPX5::is_SetTextConfiguration_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for SetTextConfiguration command.

	/*----- PROTECTED REGION ID(AmptekPX5::SetTextConfigurationStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::SetTextConfigurationStateAllowed

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_GetTextConfigurationState_allowed()
 *	Description : Execution allowed for GetTextConfiguration command.
 */
//--------------------------------------------------------

bool AmptekPX5::is_GetTextConfiguration_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for GetTextConfiguration command.

	/*----- PROTECTED REGION ID(AmptekPX5::GetTextConfigurationStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::GetTextConfigurationStateAllowed

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_EchoState_allowed()
 *	Description : Execution allowed for Echo command.
 */
//--------------------------------------------------------

bool AmptekPX5::is_Echo_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for Echo command.

	/*----- PROTECTED REGION ID(AmptekPX5::EchoStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::EchoStateAllowed

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_EnableState_allowed()
 *	Description : Execution allowed for Enable command.
 */
//--------------------------------------------------------

bool AmptekPX5::is_Enable_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for Enable command.

	/*----- PROTECTED REGION ID(AmptekPX5::EnableStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::EnableStateAllowed

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_DisableState_allowed()
 *	Description : Execution allowed for Disable command.
 */
//--------------------------------------------------------

bool AmptekPX5::is_Disable_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for Disable command.

	/*----- PROTECTED REGION ID(AmptekPX5::DisableStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::DisableStateAllowed

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_ClearSpectrumState_allowed()
 *	Description : Execution allowed for ClearSpectrum command.
 */
//--------------------------------------------------------

bool AmptekPX5::is_ClearSpectrum_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for ClearSpectrum command.

	/*----- PROTECTED REGION ID(AmptekPX5::ClearSpectrumStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::ClearSpectrumStateAllowed

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_LatchGetClearSCAState_allowed()
 *	Description : Execution allowed for LatchGetClearSCA command.
 */
//--------------------------------------------------------

bool AmptekPX5::is_LatchGetClearSCA_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for LatchGetClearSCA command.

	/*----- PROTECTED REGION ID(AmptekPX5::LatchGetClearSCAStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::LatchGetClearSCAStateAllowed

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_ClearInputBufferState_allowed()
 *	Description : Execution allowed for ClearInputBuffer command.
 */
//--------------------------------------------------------

bool AmptekPX5::is_ClearInputBuffer_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for ClearInputBuffer command.

	/*----- PROTECTED REGION ID(AmptekPX5::ClearInputBufferStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::ClearInputBufferStateAllowed

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::is_AutoTuneState_allowed()
 *	Description : Execution allowed for AutoTune command.
 */
//--------------------------------------------------------

bool AmptekPX5::is_AutoTune_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::MOVING)
	{

	/*----- PROTECTED REGION ID(AmptekPX5::AutoTuneStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::AutoTuneStateAllowed

		return false;
	}
	return true;
}


	/*----- PROTECTED REGION ID(AmptekPX5::are_dynamic_commands_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic commands are alowed

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::are_dynamic_commands_allowed

}	// namespace AmptekPX5_ns
