/*----- PROTECTED REGION ID(AmptekPX5.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        AmptekPX5.cpp
//
// description : C++ source for the AmptekPX5 and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               AmptekPX5 are implemented in this file.
//
// project :     AmptekPX5.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <AmptekPX5.h>
#include <AmptekPX5Class.h>
#include <unistd.h>
#include <stdlib.h>
#include <pthread.h>
#include <iostream> 
#include <semaphore.h>




/*----- PROTECTED REGION END -----*/


/**
 *	AmptekPX5 class description:
 *	Device server to control the MCA Amptek PX5. 
 *	The device server implements the communication by UDP socket. It can start and stop one acquisition and after read the Spectrum data. 
 *	In addition it exports some configuration attributes and a command to send ascii commands.
 *	 
 */

//================================================================
//
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name          |  Method name
//----------------------------------------------------------------
//  State                 |  dev_state
//  Status                |  Inherited (no method)
//  SetTextConfiguration  |  set_text_configuration
//  GetTextConfiguration  |  get_text_configuration
//  Echo                  |  echo
//  Enable                |  enable
//  Disable               |  disable
//  ClearSpectrum         |  clear_spectrum
//  LatchGetClearSCA      |  latch_get_clear_sca
//  ClearInputBuffer      |  clear_input_buffer
//  AutoTune              |  auto_tune
//================================================================

namespace AmptekPX5_ns
{
	/*----- PROTECTED REGION ID(AmptekPX5::namespace_starting) ENABLED START -----*/

        //      static initializations

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::namespace_starting



//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::AmptekPX5()
 *	Description : Constructors for a Tango device
 *	              implementing the class AmptekPX5
 */
//--------------------------------------------------------
AmptekPX5::AmptekPX5(Tango::DeviceClass *cl, string &s)
 	: Tango::Device_4Impl(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(AmptekPX5::constructor_1) ENABLED START -----*/

        init_device();

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::constructor_1
}
//--------------------------------------------------------
AmptekPX5::AmptekPX5(Tango::DeviceClass *cl, const char *s)
 	: Tango::Device_4Impl(cl, s)
{
	/*----- PROTECTED REGION ID(AmptekPX5::constructor_2) ENABLED START -----*/

        init_device();

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::constructor_2
}
//--------------------------------------------------------
AmptekPX5::AmptekPX5(Tango::DeviceClass *cl, const char *s, const char *d)
 	: Tango::Device_4Impl(cl, s, d)
{
	/*----- PROTECTED REGION ID(AmptekPX5::constructor_3) ENABLED START -----*/

        init_device();

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::constructor_3
}


//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::delete_device()()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void AmptekPX5::delete_device()
{
	/*----- PROTECTED REGION ID(AmptekPX5::delete_device) ENABLED START -----*/

        //      Delete device allocated objects
    delete commHandler;

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::delete_device
	delete[] attr_FastCount_read;
	delete[] attr_SlowCount_read;
	delete[] attr_AcquisitionTime_read;
	delete[] attr_CoarseGain_read;
	delete[] attr_PileupReject_read;
	delete[] attr_FlatTopWidth_read;
	delete[] attr_PeakingTime_read;
	delete[] attr_MCAC_read;
	delete[] attr_FineGain_read;
	delete[] attr_TotalGain_read;
	delete[] attr_Clock_read;
	delete[] attr_DeadTime_read;
	delete[] attr_Spectrum_read;
	
}


//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::init_device()
 *	Description : //	will be called at device initialization.
 */
//--------------------------------------------------------
void AmptekPX5::init_device()
{
	DEBUG_STREAM << "AmptekPX5::init_device() create device " << device_name << endl;

	/*----- PROTECTED REGION ID(AmptekPX5::init_device_before) ENABLED START -----*/

        //      Initialization before get_device_property() call
	thread_exists = false;

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::init_device_before
	
	//	Get the device properties (if any) from database
	get_device_property();
	
	attr_FastCount_read = new Tango::DevULong[1];
	attr_SlowCount_read = new Tango::DevULong[1];
	attr_AcquisitionTime_read = new Tango::DevDouble[1];
	attr_CoarseGain_read = new Tango::DevShort[1];
	attr_PileupReject_read = new Tango::DevString[1];
	attr_FlatTopWidth_read = new Tango::DevDouble[1];
	attr_PeakingTime_read = new Tango::DevDouble[1];
	attr_MCAC_read = new Tango::DevULong[1];
	attr_FineGain_read = new Tango::DevDouble[1];
	attr_TotalGain_read = new Tango::DevDouble[1];
	attr_Clock_read = new Tango::DevDouble[1];
	attr_DeadTime_read = new Tango::DevDouble[1];
	attr_Spectrum_read = new Tango::DevULong[8192];
	
	/*----- PROTECTED REGION ID(AmptekPX5::init_device) ENABLED START -----*/

        //      Initialize device
    try
    {
        commHandler = new AmptekCommHandler(hostname.c_str(), port, timeout, this);
    }
    catch(AmptekException& e)
    {
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::echo()"));
    }
    /*----- PROTECTED REGION END -----*/	//	AmptekPX5::init_device
}



//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::get_device_property()
 *	Description : //	Add your own code to initialize
 */
//--------------------------------------------------------
void AmptekPX5::get_device_property()
{
	/*----- PROTECTED REGION ID(AmptekPX5::get_device_property_before) ENABLED START -----*/

        //      Initialize property data members

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("Hostname"));
	dev_prop.push_back(Tango::DbDatum("Port"));
	dev_prop.push_back(Tango::DbDatum("Timeout"));
	dev_prop.push_back(Tango::DbDatum("NrOfUdpAttempts"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on AmptekPX5Class to get class property
		Tango::DbDatum	def_prop, cl_prop;
		AmptekPX5Class	*ds_class =
			(static_cast<AmptekPX5Class *>(get_device_class()));
		int	i = -1;

		//	Try to initialize Hostname from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  hostname;
		else {
			//	Try to initialize Hostname from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  hostname;
		}
		//	And try to extract Hostname value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  hostname;

		//	Try to initialize Port from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  port;
		else {
			//	Try to initialize Port from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  port;
		}
		//	And try to extract Port value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  port;

		//	Try to initialize Timeout from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  timeout;
		else {
			//	Try to initialize Timeout from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  timeout;
		}
		//	And try to extract Timeout value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  timeout;

		//	Try to initialize NrOfUdpAttempts from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  nrOfUdpAttempts;
		else {
			//	Try to initialize NrOfUdpAttempts from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  nrOfUdpAttempts;
		}
		//	And try to extract NrOfUdpAttempts value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  nrOfUdpAttempts;


	}
	/*----- PROTECTED REGION ID(AmptekPX5::get_device_property_after) ENABLED START -----*/

        //      Check device property data members init

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::get_device_property_after

}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void AmptekPX5::always_executed_hook()
{
	INFO_STREAM << "AmptekPX5::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::always_executed_hook) ENABLED START -----*/

        //      code always executed before all requests

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::always_executed_hook
}



//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::read_attr_hardware()
 *	Description : Hardware acquisition for attributes.
 */
//--------------------------------------------------------
void AmptekPX5::read_attr_hardware(vector<long> &attr_list)
{
	DEBUG_STREAM << "AmptekPX5::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_attr_hardware) ENABLED START -----*/

        //      Add your own code

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_attr_hardware

}


//--------------------------------------------------------
/**
 *	Read FastCount attribute
 *	Description: 
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_FastCount(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_FastCount(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_FastCount) ENABLED START -----*/

    Packet* requestPacket;
    Packet* responsePacket; 
    requestPacket = new Packet(MIN_PACKET_LEN);
    requestPacket->initSync();
    requestPacket->setPid1(0x01);
    requestPacket->setPid2(0x01);
    requestPacket->calcAndFillChecksum();
    responsePacket = new Packet(MIN_PACKET_LEN);
    DEBUG_STREAM << "AmptekPX5::read_FastCount()  - REQUEST: " << endl << requestPacket->toString();

    try
    {
        commHandler->sendWithReceive(requestPacket, responsePacket, nrOfUdpAttempts);
    }
    catch(AmptekException& e)
    {
        set_state(Tango::ALARM);
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::read_FastCount()"));
    }
    DEBUG_STREAM << "AmptekPX5::read_FastCount()  - RESPONSE: " << endl << responsePacket->toString();

    //validating if response packet corresponds to the request
    if (responsePacket->at(PID1) != 0x80 or responsePacket->at(PID2) != 0x01)
    {
        stringstream description;
        description << "Response of AmptekPX5 is not of correct type. State could not be retrieved.";
        interpretAcknowledge(responsePacket, &description);
        ERROR_STREAM << description.str() << endl;
        Tango::Except::throw_exception(
            static_cast<const char*> ("AMPTEK_ERROR"),
            description.str(),
            static_cast<const char*> ("AmptekPX5::read_FastCount()"));
    }

    attr_FastCount_read[0] = mergeBytes(responsePacket->at(DATA+3),
                                     responsePacket->at(DATA+2),
                                     responsePacket->at(DATA+1),
                                     responsePacket->at(DATA));

    delete requestPacket;
    delete responsePacket;

        //      Set the attribute value
        attr.set_value(attr_FastCount_read);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_FastCount
}
//--------------------------------------------------------
/**
 *	Read SlowCount attribute
 *	Description: 
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_SlowCount(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_SlowCount(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_SlowCount) ENABLED START -----*/

    Packet* requestPacket;
    Packet* responsePacket; 
    requestPacket = new Packet(MIN_PACKET_LEN);
    requestPacket->initSync();
    requestPacket->setPid1(0x01);
    requestPacket->setPid2(0x01);
    requestPacket->calcAndFillChecksum();
    responsePacket = new Packet(MIN_PACKET_LEN);
    DEBUG_STREAM << "AmptekPX5::read_SlowCount()  - REQUEST: " << endl << requestPacket->toString();

    try
    {
        commHandler->sendWithReceive(requestPacket, responsePacket, nrOfUdpAttempts);
    }
    catch(AmptekException& e)
    {
        set_state(Tango::ALARM);
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::read_SlowCount()"));
    }
    DEBUG_STREAM << "AmptekPX5::read_SlowCount()  - RESPONSE: " << endl << responsePacket->toString();

    //validating if response packet corresponds to the request
    if (responsePacket->at(PID1) != 0x80 or responsePacket->at(PID2) != 0x01)
    {
        stringstream description;
        description << "Response of AmptekPX5 is not of correct type. State could not be retrieved.";
        interpretAcknowledge(responsePacket, &description);
        ERROR_STREAM << description.str() << endl;
        Tango::Except::throw_exception(
            static_cast<const char*> ("AMPTEK_ERROR"),
            description.str(),
            static_cast<const char*> ("AmptekPX5::read_SlowCount()"));
    }

    attr_SlowCount_read[0] = mergeBytes(responsePacket->at(DATA+7),
                                     responsePacket->at(DATA+6),
                                     responsePacket->at(DATA+5),
                                     responsePacket->at(DATA+4));

    delete requestPacket;
    delete responsePacket;

        //      Set the attribute value
        attr.set_value(attr_SlowCount_read);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_SlowCount
}
//--------------------------------------------------------
/**
 *	Read AcquisitionTime attribute
 *	Description: It sets the preset acquisition time.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_AcquisitionTime(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_AcquisitionTime(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_AcquisitionTime) ENABLED START -----*/

        string result = this->read_parameter("PRET");
        *attr_AcquisitionTime_read = atof(result.c_str());

        //      Set the attribute value
        attr.set_value(attr_AcquisitionTime_read);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_AcquisitionTime
}

//--------------------------------------------------------
/**
 *	Write AcquisitionTime attribute values to hardware.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::write_AcquisitionTime(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::write_AcquisitionTime(Tango::Attribute &attr) entering... " << endl;
	
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	
	/*----- PROTECTED REGION ID(AmptekPX5::write_AcquisitionTime) ENABLED START -----*/

        std::ostringstream buff;
        buff << w_val;
        this->write_parameter("PRET", buff.str());
        this->push_change_event("AcquisitionTime",&w_val);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::write_AcquisitionTime
}

//--------------------------------------------------------
/**
 *	Read CoarseGain attribute
 *	Description: It Selects the analog gain.
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_CoarseGain(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_CoarseGain(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_CoarseGain) ENABLED START -----*/
        
        string result = this->read_parameter("GAIA");
        *attr_CoarseGain_read = atoi(result.c_str());

        //      Set the attribute value
        attr.set_value(attr_CoarseGain_read);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_CoarseGain
}

//--------------------------------------------------------
/**
 *	Write CoarseGain attribute values to hardware.
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::write_CoarseGain(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::write_CoarseGain(Tango::Attribute &attr) entering... " << endl;
	
	//	Retrieve write value
	Tango::DevShort	w_val;
	attr.get_write_value(w_val);
	
	/*----- PROTECTED REGION ID(AmptekPX5::write_CoarseGain) ENABLED START -----*/

        //      Retrieve write value
        
        std::ostringstream buff;
        buff << w_val;
        this->write_parameter("GAIA", buff.str());
        this->push_change_event("CoarseGain",&w_val);
        this->update_total_gain();
        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::write_CoarseGain
}

//--------------------------------------------------------
/**
 *	Read PileupReject attribute
 *	Description: It`s used to enable or disable Pile-up Rejection.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_PileupReject(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_PileupReject(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_PileupReject) ENABLED START -----*/

        string result = this->read_parameter("PURE");
        *attr_PileupReject_read = CORBA::string_dup(result.c_str());

                                                    //CORBA::string_dup(const_cast<char *>(confs[i].c_str()));
        //      Set the attribute value
        attr.set_value(attr_PileupReject_read);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_PileupReject
}

//--------------------------------------------------------
/**
 *	Write PileupReject attribute values to hardware.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::write_PileupReject(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::write_PileupReject(Tango::Attribute &attr) entering... " << endl;
	
	//	Retrieve write value
	Tango::DevString	w_val;
	attr.get_write_value(w_val);
	
	/*----- PROTECTED REGION ID(AmptekPX5::write_PileupReject) ENABLED START -----*/

        //      Retrieve write value
        std::ostringstream buff;
        buff << w_val;
        this->write_parameter("PURE", buff.str());
        this->push_change_event("PileupReject",&w_val);
        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::write_PileupReject
}

//--------------------------------------------------------
/**
 *	Read FlatTopWidth attribute
 *	Description: It selects the flat top width of the trapezoidal shaper. A flat top fo 0uS will result in a triangular shape, not trapezoidal.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_FlatTopWidth(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_FlatTopWidth(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_FlatTopWidth) ENABLED START -----*/

        //      Set the attribute value
        attr.set_value(attr_FlatTopWidth_read);
        string result = this->read_parameter("TFLA");
        *attr_FlatTopWidth_read = atof(result.c_str());
        //      Set the attribute value
        attr.set_value(attr_FlatTopWidth_read);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_FlatTopWidth
}

//--------------------------------------------------------
/**
 *	Write FlatTopWidth attribute values to hardware.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::write_FlatTopWidth(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::write_FlatTopWidth(Tango::Attribute &attr) entering... " << endl;
	
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	
	/*----- PROTECTED REGION ID(AmptekPX5::write_FlatTopWidth) ENABLED START -----*/

        //      Retrieve write value
        std::ostringstream buff;
        buff << w_val;
        this->write_parameter("TFLA", buff.str());
        this->push_change_event("FlatTopWidth",&w_val);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::write_FlatTopWidth
}

//--------------------------------------------------------
/**
 *	Read PeakingTime attribute
 *	Description: It selects the peaking time for the slow (shape) channel.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_PeakingTime(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_PeakingTime(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_PeakingTime) ENABLED START -----*/
        
        string result = this->read_parameter("TPEA");
        *attr_PeakingTime_read = atof(result.c_str());

        //      Set the attribute value
        attr.set_value(attr_PeakingTime_read);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_PeakingTime
}

//--------------------------------------------------------
/**
 *	Write PeakingTime attribute values to hardware.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::write_PeakingTime(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::write_PeakingTime(Tango::Attribute &attr) entering... " << endl;
	
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	
	/*----- PROTECTED REGION ID(AmptekPX5::write_PeakingTime) ENABLED START -----*/
        
        //      Retrieve write value
        std::ostringstream buff;
        
        buff << w_val;
        this->write_parameter("TPEA", buff.str());
        this->push_change_event("PeakingTime",&w_val);
        this->update_flat_top_width();
        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::write_PeakingTime
}

//--------------------------------------------------------
/**
 *	Read MCAC attribute
 *	Description: 
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_MCAC(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_MCAC(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_MCAC) ENABLED START -----*/
        
        string result = this->read_parameter("MCAC");
        *attr_MCAC_read = atoi(result.c_str());
        //      Set the attribute value
        attr.set_value(attr_MCAC_read);



        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_MCAC
}

//--------------------------------------------------------
/**
 *	Write MCAC attribute values to hardware.
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::write_MCAC(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::write_MCAC(Tango::Attribute &attr) entering... " << endl;
	
	//	Retrieve write value
	Tango::DevULong	w_val;
	attr.get_write_value(w_val);
	
	/*----- PROTECTED REGION ID(AmptekPX5::write_MCAC) ENABLED START -----*/
        //      Retrieve write value
        std::ostringstream buff;
        buff << w_val;
        this->write_parameter("MCAC", buff.str());
        this->push_change_event("MCAC",&w_val);
        
        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::write_MCAC
}

//--------------------------------------------------------
/**
 *	Read FineGain attribute
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_FineGain(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_FineGain(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_FineGain) ENABLED START -----*/

        string result = this->read_parameter("GAIF");
        DEBUG_STREAM << result << endl;
        *attr_FineGain_read = atof(result.c_str());

        //      Set the attribute value
        attr.set_value(attr_FineGain_read);

        
        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_FineGain
}

//--------------------------------------------------------
/**
 *	Write FineGain attribute values to hardware.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::write_FineGain(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::write_FineGain(Tango::Attribute &attr) entering... " << endl;
	
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	
	/*----- PROTECTED REGION ID(AmptekPX5::write_FineGain) ENABLED START -----*/

        //      Retrieve write value
        std::ostringstream buff;
        buff << w_val;
        this->write_parameter("GAIF", buff.str());
        this->push_change_event("FineGain",&w_val);
        this->update_total_gain();
        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::write_FineGain
}

//--------------------------------------------------------
/**
 *	Read TotalGain attribute
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_TotalGain(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_TotalGain(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_TotalGain) ENABLED START -----*/

        //      Set the attribute value

        string result = this->read_parameter("GAIN");
        *attr_TotalGain_read = atoi(result.c_str());

        attr.set_value(attr_TotalGain_read);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_TotalGain
}
//--------------------------------------------------------
/**
 *	Read Clock attribute
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_Clock(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_Clock(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_Clock) ENABLED START -----*/
        string result = this->read_parameter("CLCK");
        *attr_Clock_read = atoi(result.c_str());

        //      Set the attribute value
        attr.set_value(attr_Clock_read);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_Clock
}

//--------------------------------------------------------
/**
 *	Write Clock attribute values to hardware.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::write_Clock(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::write_Clock(Tango::Attribute &attr) entering... " << endl;
	
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	
	/*----- PROTECTED REGION ID(AmptekPX5::write_Clock) ENABLED START -----*/

        std::ostringstream buff;
        buff << w_val;
        this->write_parameter("CLCK", buff.str());
        this->push_change_event("Clock",&w_val);
        this->update_flat_top_width();
        this->update_peaking_time();

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::write_Clock
}

//--------------------------------------------------------
/**
 *	Read DeadTime attribute
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar 
 */
//--------------------------------------------------------
void AmptekPX5::read_DeadTime(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_DeadTime(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_DeadTime) ENABLED START -----*/

        //      Set the attribute value
    if (attr_FastCount_read[0]>0)
    {
        attr_DeadTime_read[0] = (float((attr_FastCount_read[0] - attr_SlowCount_read[0]))/attr_FastCount_read[0]) * Tango::DevULong(100);
        attr.set_value(attr_DeadTime_read);
    }
    else
    {
    attr_DeadTime_read[0] = 1000;
    attr.set_value(attr_DeadTime_read);
    }

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_DeadTime
}
//--------------------------------------------------------
/**
 *	Read Spectrum attribute
 *	Description: 
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Spectrum  max = 8192
 */
//--------------------------------------------------------
void AmptekPX5::read_Spectrum(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmptekPX5::read_Spectrum(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::read_Spectrum) ENABLED START -----*/
    Packet* requestPacket;
    Packet* responsePacket;

    requestPacket = new Packet(MIN_PACKET_LEN);
    requestPacket->initSync();
    requestPacket->setPid1(0x02);
    requestPacket->setPid2(0x01);
    requestPacket->calcAndFillChecksum();
    DEBUG_STREAM << "AmptekPX5::read_Spectrum(): REQUEST: " << endl << requestPacket->toString();
    responsePacket = new Packet(6);

    try
    {
        commHandler->sendWithReceiveSpectrum(requestPacket, responsePacket, nrOfUdpAttempts);
    }
    catch(AmptekException& e)
    {
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
            static_cast<const char*> ("AMPTEK_ERROR"),
            e.description().c_str(),
            static_cast<const char*> ("AmptekPX5::read_Spectrum()"));
    }

    DEBUG_STREAM << "AmptekPX5::read_Spectrum(): RESPONSE: " << endl << responsePacket->toString();
    //validating if response packet corresponds to the request
    if(responsePacket->at(PID1) != 0x81)
    {
        stringstream description;
        description << "Response of AmptekPX5 is not of correct type.";
        interpretAcknowledge(responsePacket, &description); 
        ERROR_STREAM << description.str() << endl;
        Tango::Except::throw_exception(
            static_cast<const char*> ("AMPTEK_ERROR"),
            description.str(),
            static_cast<const char*> ("AmptekPX5::read_Spectrum()"));
    }

    //copying data into spectrum attr
    unsigned short dataLen = responsePacket->calcLen();
    unsigned short spectrumLen = dataLen / 3;

    for (int dataIdx = 0, spctrIdx = 0; dataIdx < dataLen; dataIdx+=3, spctrIdx++)
        attr_Spectrum_read[spctrIdx] = mergeBytes(responsePacket->at(dataIdx+DATA+2), \
                                                  responsePacket->at(dataIdx+DATA+1), \
                                                  responsePacket->at(dataIdx+DATA));

    delete requestPacket;
    delete responsePacket;

        //      Set the attribute value
        attr.set_value(attr_Spectrum_read, spectrumLen);

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::read_Spectrum
}

//--------------------------------------------------------
/**
 *	Method      : AmptekPX5::AmptekPX5Class::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *	              for specified device.
 */
//--------------------------------------------------------
void AmptekPX5::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(AmptekPX5::Class::add_dynamic_attributes) ENABLED START -----*/

	//	Add your own code to create and add dynamic attributes if any

	/*----- PROTECTED REGION END -----*/	//	AmptekPX5::Class::add_dynamic_attributes

}



//========================================================
//	Command execution methods
//========================================================

//--------------------------------------------------------
/**
 *	Execute the State command:
 *	Description: This command gets the device state (stored in its device_state data member) and returns it to the caller.
 *
 *	@param argin none
 *	@returns Device state
 */
//--------------------------------------------------------
Tango::DevState AmptekPX5::dev_state()
{
	DEBUG_STREAM << "AmptekPX5::State()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::dev_state) ENABLED START -----*/

        Tango::DevState argout = DeviceImpl::dev_state();
                //      Add your own state management
    Packet* requestPacket;
    Packet* responsePacket; 
    requestPacket = new Packet(MIN_PACKET_LEN);
    requestPacket->initSync();
    requestPacket->setPid1(0x01);
    requestPacket->setPid2(0x01);
    requestPacket->calcAndFillChecksum();
    responsePacket = new Packet(MIN_PACKET_LEN);
    DEBUG_STREAM << "AmptekPX5::State()  - REQUEST: " << endl << requestPacket->toString();

    try
    {
        commHandler->sendWithReceive(requestPacket, responsePacket, nrOfUdpAttempts);
    }
    catch(AmptekException& e)
    {
        set_state(Tango::ALARM);
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::echo()"));
    }
    DEBUG_STREAM << "AmptekPX5::State()  - RESPONSE: " << endl << responsePacket->toString();

    //validating if response packet corresponds to the request
    if (responsePacket->at(PID1) != 0x80 or responsePacket->at(PID2) != 0x01)
    {
        stringstream description;
        description << "Response of AmptekPX5 is not of correct type. State could not be retrieved.";
        interpretAcknowledge(responsePacket, &description);
        ERROR_STREAM << description.str() << endl;
        Tango::Except::throw_exception(
            static_cast<const char*> ("AMPTEK_ERROR"),
            description.str(),
            static_cast<const char*> ("AmptekPX5::get_text_configuration()"));
    }

    byte byte35 = responsePacket->at(DATA+35);
    byte state = (byte(0b00100000) & byte35);

    if(state == 32)
        argout = Tango::MOVING;
    else
        argout = Tango::ON;

    delete requestPacket;
    delete responsePacket;

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::dev_state

	set_state(argout);               // Give the state to Tango.
	return DeviceImpl::dev_state();  // Return it after Tango management.

}

//--------------------------------------------------------
/**
 *	Execute the SetTextConfiguration command:
 *	Description: 
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
void AmptekPX5::set_text_configuration(const Tango::DevVarStringArray *argin)
{
	DEBUG_STREAM << "AmptekPX5::SetTextConfiguration()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::set_text_configuration) ENABLED START -----*/

        //      Add your own code
    stringstream conf;
    for (unsigned int i = 0; i < argin->length(); i++)
    {
        //TODO: implement validation mechanism
        conf << (*argin)[i].in() << ";";
    }

    Packet* requestPacket;
    Packet* responsePacket;
    requestPacket = new Packet(MIN_PACKET_LEN);
    requestPacket->initSync();
    requestPacket->setPid1(0x20);
    requestPacket->setPid2(0x02);
    int len = conf.str().length();
    byte data[len];
    charToByte(conf.str().c_str(), data, len);
    requestPacket->setData(data, len);
    requestPacket->calcAndFillChecksum();

    DEBUG_STREAM << "AmptekPX5::SetTextConfiguration(): SET TEXT CONFIGURATION REQUEST: " 
                 << endl << requestPacket->toString();
    responsePacket = new Packet(MIN_PACKET_LEN);
    try
    {
        commHandler->sendWithReceive(requestPacket, responsePacket, nrOfUdpAttempts);
    }
    catch(AmptekException& e)
    {
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::set_text_configuration()"));
    }
    DEBUG_STREAM << "AmptekPX5::SetTextConfiguration(): SET TEXT CONFIGURATION RESPONSE: " 
                 << endl << responsePacket->toString();

    //interpretting acknowledge response
    stringstream description;
    bool ackOK = interpretAcknowledge(responsePacket, &description);
    if (!ackOK)
    {
        ERROR_STREAM << description.str() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                description.str(),
                static_cast<const char*> ("AmptekPX5::set_text_configuration()"));
    }

    delete requestPacket;
    delete responsePacket; 

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::set_text_configuration

}

//--------------------------------------------------------
/**
 *	Execute the GetTextConfiguration command:
 *	Description: 
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevVarStringArray *AmptekPX5::get_text_configuration(const Tango::DevVarStringArray *argin)
{
	Tango::DevVarStringArray *argout;
	DEBUG_STREAM << "AmptekPX5::GetTextConfiguration()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::get_text_configuration) ENABLED START -----*/

        //      Add your own code
    stringstream conf;
    for (unsigned int i = 0; i < argin->length(); i++)
    {
        conf << (*argin)[i].in() << ";";
    }

    Packet* requestPacket;
    Packet* responsePacket; 
    requestPacket = new Packet(MIN_PACKET_LEN);
    requestPacket->initSync();
    requestPacket->setPid1(0x20);
    requestPacket->setPid2(0x03);
    int requestLen = conf.str().length();
    byte requestData[requestLen];
    charToByte(conf.str().c_str(), requestData, requestLen);
    requestPacket->setData(requestData, requestLen);
    requestPacket->calcAndFillChecksum();
    DEBUG_STREAM << "AmptekPX5::GetTextConfiguration() - REQUEST: " << endl << requestPacket->toString();
    responsePacket = new Packet(MIN_PACKET_LEN);

    try
    {
        commHandler->sendWithReceive(requestPacket, responsePacket, nrOfUdpAttempts);
    }
    catch(AmptekException& e)
    {
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::get_text_configuration()"));
    }
    DEBUG_STREAM << "AmptekPX5::GetTextConfiguration() - RESPONSE: " << endl << responsePacket->toString();

    //validating if response packet corresponds to the request
    if (responsePacket->at(PID1) != 0x82 or responsePacket->at(PID2) != 0x07)
    {
        stringstream description;
        description << "Response of AmptekPX5 is not of correct type. Configuration could not be retrieved.";
        interpretAcknowledge(responsePacket, &description);
        ERROR_STREAM << description.str() << endl;
        Tango::Except::throw_exception(
            static_cast<const char*> ("AMPTEK_ERROR"),
            description.str(),
            static_cast<const char*> ("AmptekPX5::get_text_configuration()"));
    }

    //splitting response data
    int responseLen = responsePacket->dataLength;
    DEBUG_STREAM << "get_text_configuration(): responsePacket data lenght = " << responseLen << endl;
    char responseData[responseLen+1]; // adding one char for terminating NULL
    byteToChar(&(responsePacket->at(DATA)), responseData, responseLen);
    DEBUG_STREAM << "get_text_configuration(): Data = " << string(responseData) 
                 << "; Lenght of data = " << strlen(responseData) << endl;
    vector<string> confs;
    char* pch;
    pch = strtok (responseData,";");
    while (pch != NULL)
    {
        confs.push_back(string(pch));
        pch = strtok(NULL, ";");
    }

    //copying configuration into argout
    argout = new Tango::DevVarStringArray();
    argout->length(confs.size());

    for(unsigned int i = 0; i < confs.size(); i++)
        (*argout)[i] = CORBA::string_dup(const_cast<char *>(confs[i].c_str()));

    delete requestPacket;
    delete responsePacket; 

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::get_text_configuration

	return argout;
}

//--------------------------------------------------------
/**
 *	Execute the Echo command:
 *	Description: 
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevString AmptekPX5::echo(Tango::DevString argin)
{
	Tango::DevString argout;
	DEBUG_STREAM << "AmptekPX5::Echo()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::echo) ENABLED START -----*/
    //  Add your own code

    Packet* requestPacket;
    Packet* responsePacket;     

    requestPacket = new Packet(MIN_PACKET_LEN);
    requestPacket->initSync();
    requestPacket->setPid1(0xF1);
    requestPacket->setPid2(0x7F);

    unsigned short data_len = strlen(argin);
    byte data[data_len];
    charToByte(argin, data, data_len);
    requestPacket->setData(data, data_len);
    requestPacket->calcAndFillChecksum();
    DEBUG_STREAM << "AmptekPX5::Echo()  - REQUEST: " << endl << requestPacket->toString();
    responsePacket = new Packet(MIN_PACKET_LEN);

    try
    {
        commHandler->sendWithReceive(requestPacket, responsePacket, nrOfUdpAttempts);
    }
    catch(AmptekException& e)
    {
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::echo()"));
    }
    DEBUG_STREAM << "AmptekPX5::Echo()  - RESPONSE: " << endl << responsePacket->toString();

    //validating if response packet corresponds to the request
    if (responsePacket->at(PID1) != 0x8F or responsePacket->at(PID2) != 0x7F)
    {
        stringstream description;
        description << "Response of AmptekPX5 is not of correct type. Configuration could not be retrieved.";
        interpretAcknowledge(responsePacket, &description);
        ERROR_STREAM << description.str() << endl;
        Tango::Except::throw_exception(
            static_cast<const char*> ("AMPTEK_ERROR"),
            description.str(),
            static_cast<const char*> ("AmptekPX5::get_text_configuration()"));
    }

    int len = responsePacket->dataLength;
    argout = new char[len+1]; //adding one char for terminating NULL
    byteToChar(&(responsePacket->at(DATA)), argout, len);

    delete requestPacket;
    delete responsePacket;
        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::echo

	return argout;
}

//--------------------------------------------------------
/**
 *	Execute the Enable command:
 *	Description: 
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
void AmptekPX5::enable()
{
	DEBUG_STREAM << "AmptekPX5::Enable()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::enable) ENABLED START -----*/

        //      Add your own code
    Packet* requestPacket = new Packet(MIN_PACKET_LEN);
    requestPacket->initSync();
    requestPacket->setPid1(0xF0);
    requestPacket->setPid2(0x02);
    requestPacket->calcAndFillChecksum();
    DEBUG_STREAM << "AmptekPX5::Enable()  - REQUEST: " << endl << requestPacket->toString() << endl;
    Packet* responsePacket = new Packet(MIN_PACKET_LEN);

    try
    {
        commHandler->sendWithReceive(requestPacket, responsePacket, nrOfUdpAttempts);
    }
    catch(AmptekException& e)
    {
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::echo()"));
    }
    DEBUG_STREAM << "AmptekPX5::Enable()  - RESPONSE: " << endl << responsePacket->toString() << endl;

    //interpretting acknowledge response
    stringstream description;
    bool ackOK = interpretAcknowledge(responsePacket, &description);
    if (!ackOK)
    {
        ERROR_STREAM << description.str() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                description.str(),
                static_cast<const char*> ("AmptekPX5::set_text_configuration()"));
    }

    delete requestPacket;
    delete responsePacket;

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::enable

}

//--------------------------------------------------------
/**
 *	Execute the Disable command:
 *	Description: 
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
void AmptekPX5::disable()
{
	DEBUG_STREAM << "AmptekPX5::Disable()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::disable) ENABLED START -----*/

        //      Add your own code
    Packet* requestPacket = new Packet(MIN_PACKET_LEN);
    requestPacket->initSync();
    requestPacket->setPid1(0xF0);
    requestPacket->setPid2(0x03);
    requestPacket->calcAndFillChecksum();
    Packet* responsePacket = new Packet(MIN_PACKET_LEN);

    DEBUG_STREAM << "AmptekPX5::Disable() - REQUEST: " << endl << requestPacket->toString() << endl;
    try
    {
        commHandler->sendWithReceive(requestPacket, responsePacket, nrOfUdpAttempts);
    }
    catch(AmptekException& e)
    {
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::echo()"));
    }
    DEBUG_STREAM << "AmptekPX5::Disable() - RESPONSE: " << endl << responsePacket->toString() << endl;

    //interpretting acknowledge response
    stringstream description;
    bool ackOK = interpretAcknowledge(responsePacket, &description);
    if (!ackOK)
    {
        ERROR_STREAM << description.str() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                description.str(),
                static_cast<const char*> ("AmptekPX5::set_text_configuration()"));
    }
    delete requestPacket;
    delete responsePacket;

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::disable

}

//--------------------------------------------------------
/**
 *	Execute the ClearSpectrum command:
 *	Description: 
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
void AmptekPX5::clear_spectrum()
{
	DEBUG_STREAM << "AmptekPX5::ClearSpectrum()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::clear_spectrum) ENABLED START -----*/

        //      Add your own code
    Packet* requestPacket = new Packet(MIN_PACKET_LEN);
    requestPacket->initSync();
    requestPacket->setPid1(0xF0);
    requestPacket->setPid2(0x01);
    requestPacket->calcAndFillChecksum();
    DEBUG_STREAM << "AmptekPX5::ClearSpectrum() - REQUEST: " << endl << requestPacket->toString() << endl;
    Packet* responsePacket = new Packet(MIN_PACKET_LEN);

    try
    {
        commHandler->sendWithReceive(requestPacket, responsePacket, nrOfUdpAttempts);
    }
    catch(AmptekException& e)
    {
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::echo()"));
    }
    DEBUG_STREAM << "AmptekPX5::ClearSpectrum()  - RESPONSE: " << endl << responsePacket->toString() << endl;

    //interpretting acknowledge response
    stringstream description;
    bool ackOK = interpretAcknowledge(responsePacket, &description);
    if (!ackOK)
    {
        ERROR_STREAM << description.str() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                description.str(),
                static_cast<const char*> ("AmptekPX5::set_text_configuration()"));
    }
    delete requestPacket;
    delete responsePacket;

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::clear_spectrum

}

//--------------------------------------------------------
/**
 *	Execute the LatchGetClearSCA command:
 *	Description: 
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevVarULongArray *AmptekPX5::latch_get_clear_sca()
{
	Tango::DevVarULongArray *argout;
	DEBUG_STREAM << "AmptekPX5::LatchGetClearSCA()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::latch_get_clear_sca) ENABLED START -----*/

        //      Add your own code

    Packet* requestPacket;
    Packet* responsePacket; 
    requestPacket = new Packet(MIN_PACKET_LEN);
    requestPacket->initSync();
    requestPacket->setPid1(0x04);
    requestPacket->setPid2(0x03);
    requestPacket->calcAndFillChecksum();
    DEBUG_STREAM << "AmptekPX5::LatchGetClearSCA() - REQUEST: " << endl << requestPacket->toString();
    responsePacket = new Packet(MIN_PACKET_LEN);

    try
    {
        commHandler->sendWithReceive(requestPacket, responsePacket, nrOfUdpAttempts);
    }
    catch(AmptekException& e)
    {
        ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AMPTEK_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::latch_get_clear_sca()"));
    }
    DEBUG_STREAM << "AmptekPX5::LatchGetClearSCA() - RESPONSE: " << endl << responsePacket->toString();

    //validating if response packet corresponds to the request
    if (responsePacket->at(PID1) != 0x83 or responsePacket->at(PID2) != 0x01)
    {
        stringstream description;
        description << "Response of AmptekPX5 is not of correct type. Configuration could not be retrieved.";
        interpretAcknowledge(responsePacket, &description);
        ERROR_STREAM << description.str() << endl;
        Tango::Except::throw_exception(
            static_cast<const char*> ("AMPTEK_ERROR"),
            description.str(),
            static_cast<const char*> ("AmptekPX5::latch_get_clear_sca()"));
    }

    //mergin sca data
    unsigned int dataLen = responsePacket->dataLength;
    unsigned int scaLen = dataLen/4;
    unsigned long buffer[scaLen];
    for (unsigned int i = 0; i < scaLen; i++)
        buffer[i] = 0;

    DEBUG_STREAM << "AmptekPX5::LatchGetClearSCA() - responsePacket data length = " << dataLen << endl;

    for (unsigned int dataIdx = 0, scaIdx = 0; dataIdx < dataLen; dataIdx+=4, scaIdx++)
        buffer[scaIdx] = mergeBytes(responsePacket->at(dataIdx+DATA+3),
                                    responsePacket->at(dataIdx+DATA+2),
                                    responsePacket->at(dataIdx+DATA+1),
                                    responsePacket->at(dataIdx+DATA));

    for (unsigned int i =0; i < scaLen; i++)
        DEBUG_STREAM << "buffer[" << i << "]=" << buffer[i] << endl;
    DEBUG_STREAM << "AmptekPX5::LatchGetClearSCA() - after merging sca data" << endl;

    argout = new Tango::DevVarULongArray();

    argout->length(scaLen);
    for (unsigned int i = 0;i < scaLen;i++)
          (*argout)[i] = buffer[i];

    delete requestPacket;
    delete responsePacket;
        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::latch_get_clear_sca

	return argout;
}

//--------------------------------------------------------
/**
 *	Execute the ClearInputBuffer command:
 *	Description: Clears the socket from any buffered incoming data.
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
void AmptekPX5::clear_input_buffer()
{
	DEBUG_STREAM << "AmptekPX5::ClearInputBuffer()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::clear_input_buffer) ENABLED START -----*/

        //      Add your own code
    commHandler->clearInputBuffer();
        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::clear_input_buffer

}

//--------------------------------------------------------
/**
 *	Execute the AutoTune command:
 *	Description: This Command execute AutoTune Process
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
void AmptekPX5::auto_tune()
{
	DEBUG_STREAM << "AmptekPX5::AutoTune()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmptekPX5::auto_tune) ENABLED START -----*/

        //      Add your own code
    cout<<"thread exist: "<<thread_exists<<endl;
    if (thread_exists == false) {
        cout<<"Entrando al Thread"<<endl;
        pthread_t thread_Auto_Tune;
        pthread_create(&thread_Auto_Tune, NULL, &(Auto_Tune_Thread), this);
        pthread_detach(thread_Auto_Tune);
        thread_exists = true;
    }
    else
    {
        cout<<"sending exception"<<endl;





     /*Tango::Except::throw_exception(
        static_cast<const char*> ("AUTOTUNE in progress..."), static_cast<const char*> (""), static_cast<const char*> ("")) ;
                //e.description().c_str();
                //static_cast<const char*> ("AmptekPX5::autotune_thread()")); */
    }

        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::auto_tune

}


	/*----- PROTECTED REGION ID(AmptekPX5::namespace_ending) ENABLED START -----*/

        //      Additional Methods
//--------------------------------------------------------
/**
 *      Execute the ReadParameter command:
 *      Description:
 *
 *      @param argin 
 *      @returns argout
 */
//--------------------------------------------------------

std::string AmptekPX5::read_parameter(std::string cmd)
{
        DEBUG_STREAM << "ReadParameter  - " << cmd << endl;
        Tango::DevVarStringArray *send_cmd, *result;
        string argout = cmd;

        send_cmd = new Tango::DevVarStringArray();
        send_cmd->length(1);
        (*send_cmd)[0] = CORBA::string_dup(cmd.c_str());
        result = this->get_text_configuration(send_cmd);
        argout = CORBA::string_dup((*result)[0]);
        
        
        if(argout.find(cmd)!=string::npos){
          DEBUG_STREAM << "ReadParameter recived: " << argout << endl;
          int len = cmd.length()+1; //cmd+"="
          argout.erase(0,len);
          DEBUG_STREAM << "ReadParameter value: " << argout << endl;
        }         
        else{
        stringstream description;
        description << "Response of AmptekPX5 is not of correct type.";
        Tango::Except::throw_exception(
            static_cast<const char*> ("AMPTEK_ERROR"),
            description.str(),
            static_cast<const char*> ("AmptekPX5::read_parameter()"));
        }
        delete(send_cmd);
        return argout;
}  


//--------------------------------------------------------
/**
 *      Execute the WriteParamter command:
 *      Description: 
 *
 *      @param argin 
 *      @returns 
 */
//--------------------------------------------------------
void AmptekPX5::write_parameter(std::string cmd, std::string value)
{

        DEBUG_STREAM << "WriteParameter -( " << cmd << "," << value <<")\n";
        
        Tango::DevVarStringArray *send_cmd;
        
        send_cmd = new Tango::DevVarStringArray();
        send_cmd->length(1);
        cmd = cmd+"="+value;
        DEBUG_STREAM << "WriteParameter cmd: " << cmd << endl;
        (*send_cmd)[0] = CORBA::string_dup(cmd.c_str());
        
        this->set_text_configuration(send_cmd);
        delete(send_cmd);

}

//--------------------------------------------------------
/**
 *      Execute the UpdateTotalGain command:
 *      Description: 
 *
 *      @param argin 
 *      @returns 
 */
//--------------------------------------------------------
void AmptekPX5::update_total_gain()
{
        string result = this->read_parameter("GAIN");
        *attr_TotalGain_read = atoi(result.c_str());

        this->push_change_event("TotalGain",attr_TotalGain_read);

}

//--------------------------------------------------------
/**
 *      Execute the UpdateFlatTopWidth command:
 *      Description: 
 *
 *      @param argin 
 *      @returns 
 */
//--------------------------------------------------------
void AmptekPX5::update_flat_top_width()
{
        string result = this->read_parameter("TFLA");
        *attr_FlatTopWidth_read = atof(result.c_str());

        this->push_change_event("FlatTopWidth",attr_FlatTopWidth_read);

}

//--------------------------------------------------------
/**
 *      Execute the UpdatePeakingTime command:
 *      Description: 
 *
 *      @param argin 
 *      @returns 
 */
//--------------------------------------------------------
void AmptekPX5::update_peaking_time()
{
        string result = this->read_parameter("TPEA");
        *attr_PeakingTime_read = atof(result.c_str());

        this->push_change_event("PeakingTime",attr_PeakingTime_read);

}

//--------------------------------------------------------
/**
 *  Function of the Thread Auto_Tune_Thread command:
 *  Description: 
 *
 *  @param argin 
 *  @returns 
 */
//--------------------------------------------------------
void* AmptekPX5::Auto_Tune_Thread(void *arg)
{
	
	AmptekPX5* amptek_klass = (AmptekPX5*) arg;
  try{  

        amptek_klass->write_parameter("PURE", "OFF");
        amptek_klass->write_parameter("PRET", "0");
        amptek_klass->enable();
        sleep(0.5);
        Packet* requestPacket = new Packet(MIN_PACKET_LEN);
        requestPacket->initSync();
        requestPacket->setPid1(0xF0);
        requestPacket->setPid2(6);
        requestPacket->calcAndFillChecksum();
        cout << "AmptekPX5::Auto_Tune_Thread() - REQUEST: " << endl;
        Packet* responsePacket = new Packet(MIN_PACKET_LEN);

        try
            {
            amptek_klass->commHandler->sendWithReceive(requestPacket, responsePacket,  amptek_klass->nrOfUdpAttempts);
            }
        catch(AmptekException& e)
            {
                amptek_klass-> set_state(Tango::ALARM);
                cout << e.description() << endl;
                Tango::Except::throw_exception(
                        static_cast<const char*> ("AMPTEK_ERROR"),
                        e.description().c_str(),
                        static_cast<const char*> ("AmptekPX5::Auto_Tune_Thread()"));
            }
            cout << "AmptekPX5::Auto_Tune_Thread()  - RESPONSE: " << endl;

            //validating if response packet corresponds to the request
            if (responsePacket->at(PID1) != 0xFF or responsePacket->at(PID2) != 0)
            {
                stringstream description;
                description << "Response of AmptekPX5 is not of correct type. State could not be retrieved.";
                interpretAcknowledge(responsePacket, &description);
                cout << description.str() << endl;
            }

        
            //Part of the Status Packet
            int count = 1 ;  
            while (true){  
                sleep(0.5);
                Packet* requestPacket = new Packet(MIN_PACKET_LEN);
                requestPacket->initSync();
                requestPacket->setPid1(1);
                requestPacket->setPid2(1);
                requestPacket->calcAndFillChecksum();
                Packet* responsePacket = new Packet(MIN_PACKET_LEN);
                cout << "Auto_Tune_Thread(), Waiting to end AutoFastThreshold - REQUEST:  "<< count << endl;
                try
                    {
                    amptek_klass->commHandler->sendWithReceive(requestPacket, responsePacket,  amptek_klass->nrOfUdpAttempts);
                    }
                catch(AmptekException& e)
                    {
                        amptek_klass-> set_state(Tango::ALARM);
                        cout << e.description() << endl;
                        Tango::Except::throw_exception(
                                static_cast<const char*> ("AMPTEK_ERROR"),
                                e.description().c_str(),
                                static_cast<const char*> ("AmptekPX5::Auto_Tune_Thread()"));
                    }

                bool  autoTuneStatus = (responsePacket->at(DATA+35) & 0x40)==0 ? false : true;
                if (autoTuneStatus) {
                    break;
                }
                count++;
                delete requestPacket;
                delete responsePacket;
            }
            

            //Part of the threshold Shaped channel
            int max_SCA_point = 512;

            //Configure SCA 15 channels, low to 0 and high to 512
            std::string cmdSCAI = "SCAI=15";
            std::string cmdSCAL = "SCAL=0";
            std::string cmdSCAH = "SCAH=512";

            Tango::DevVarStringArray *send_cmd;       
            send_cmd = new Tango::DevVarStringArray();
            send_cmd->length(3);
            (*send_cmd)[0] = CORBA::string_dup(cmdSCAI.c_str());
            (*send_cmd)[1]  = CORBA::string_dup(cmdSCAL.c_str());
            (*send_cmd)[2]  = CORBA::string_dup(cmdSCAH.c_str());
            amptek_klass->set_text_configuration(send_cmd);


            cout << "Entering to while of autoShaped Channel:  "<< endl;   
            Tango::DevVarULongArray *argout;
            argout = new Tango::DevVarULongArray();


            //Initialize the values to evaluate the THSL
            float maxTHSL = 24.9;
            float minTHSL = 0;
            float THSL = 12.5;
            int sca_number = 1000;
            int last0 = sca_number;
            int last1 = sca_number;
            int last2 = sca_number;
            int last3 = sca_number;
            
            //Number of intents fot set THSL to get the best configuration.
            int intents = 20;

            //Tolerance in the channels for the THSL 
            int tol = 1;
            count=1;

            while ((last0 >tol || last1 >tol || last2 >tol || last3>tol)&& count!=intents){
                cout << endl;
                std::ostringstream buff;
                buff << THSL;
                amptek_klass->write_parameter("THSL", buff.str());
                cout << count<< ": Setting THSL TO:  "<< buff.str() << endl; 
                sleep(0.5);
                argout = amptek_klass->latch_get_clear_sca();
                sca_number = argout[0][15];

            

                if (sca_number==0){maxTHSL = THSL;}
                else{minTHSL = THSL;}

                THSL = ((minTHSL+maxTHSL)/2);
                //cout << "minTHSL: " << minTHSL<<endl;
                //cout << "maxTHSL: " << maxTHSL<<endl;
                //cout << "THSL: " << THSL<<endl;
                count++;
                last3 = last2;
                last2 = last1;
                last1 = last0;
                last0 = sca_number;
                cout << last3<<": "<<last2<<": "<<last1<<": "<<last0 <<endl;
            }
            
            //Check if the max THSL is bigger than 24.9
            cout << "Filter applied in  THSL: " << THSL <<  endl;
            if (count>19){
                cout << "\nAutoTune not completed successfully\n";
                amptek_klass-> set_state(Tango::ALARM);
                stringstream description;
                description << "AutoTune not finished well, please, check the configuration anf try again.";
                Tango::Except::throw_exception(
                    static_cast<const char*> ("AMPTEK_ERROR"),
                    description.str(),
                    static_cast<const char*> ("AmptekPX5::autoTune_thread()"));
                }
            else{
                cout << "\nAutoTune Completed\n";}
            amptek_klass->disable();

    }
    catch(AmptekException& e)
    {
        //ERROR_STREAM << e.description() << endl;
        Tango::Except::throw_exception(
                static_cast<const char*> ("AUTOTUNE_ERROR"),
                e.description().c_str(),
                static_cast<const char*> ("AmptekPX5::autotune_thread()"));
    }
     amptek_klass->thread_exists = false;
 
}






        /*----- PROTECTED REGION END -----*/	//	AmptekPX5::namespace_ending
} //	namespace
